1. Student Marks Array

In [1]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Array:", marks)
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Array: [78 65 89 56 92]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


2. Student Marks Access

In [2]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("Marks:", marks)

print("First student:", marks[0])
print("Third student:", marks[2])
print("Second to fourth:", marks[1:4])
print("Last two students:", marks[-2:])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Second to fourth: [85 64 90]
Last two students: [90 76]


3. Subject-wise Marks

In [3]:
import numpy as np

marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

matrix = marks.reshape(5, 3)

print("Marks Matrix:")
print(matrix)

Marks Matrix:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


4. Internal and External Marks

In [4]:
import numpy as np

internal = np.array([25, 22, 24, 20, 23])
external = np.array([65, 70, 68, 72, 64])

final_marks = internal + external

print("Internal Marks:", internal)
print("External Marks:", external)
print("Final Marks:", final_marks)

Internal Marks: [25 22 24 20 23]
External Marks: [65 70 68 72 64]
Final Marks: [90 92 92 92 87]


5. Pass Percentage Analysis

In [5]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

passed = marks[marks >= 50]

print("Marks:", marks)
print("Students scoring 50 or above:", passed)

Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]


6. Average Marks

In [6]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)

print("Average marks of each student:")
print(average)

Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


7. Class Performance Statistics

In [7]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


8. Subject-wise Performance

In [8]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Total marks in each subject:")
print(subject_total)

Total marks in each subject:
[382 399 416]


9. Student-wise Performance

In [9]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)

print("Total marks of each student:")
print(student_total)

Total marks of each student:
[253 217 263 188 276]


10. Student Ranking

In [10]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])

sorted_indices = np.argsort(marks)[::-1]

print("Ranking:")

for rank, index in enumerate(sorted_indices, start=1):
    print("Rank", rank, "- Student", index + 1,
          "- Marks:", marks[index])

Ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


11. Duplicate Marks Analysis

In [11]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Original marks:", marks)
print("Unique marks:", unique_marks)

Original marks: [85 92 85 76 92]
Unique marks: [76 85 92]


12. Missing Marks

In [12]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average without missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average without missing value: 80.5


13. Grade Classification

In [13]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60,
        marks >= 50
    ],
    [
        "A+",
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A+' 'A' 'B' 'C' 'F']


14. Random Marks Generation

In [14]:
import numpy as np

np.random.seed(10)

marks = np.random.randint(0, 101, 5)

print("Random marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Random marks: [  9 100  15  64  28]
Total: 216
Average: 43.2
Highest: 100
Lowest: 9
Standard deviation: 34.219292803913994


15. Student Performance Analysis

In [16]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

highest = np.max(marks, axis=1)

lowest = np.min(marks, axis=1)

class_average = np.mean(marks)

above_average = np.where(average > class_average)[0] + 1

print("Student Performance Analysis")
print("--------------------------------")

for i in range(5):
    print("Student", i + 1)
    print("Total:", total[i])
    print("Average:", average[i])
    print("Highest:", highest[i])
    print("Lowest:", lowest[i])
    print()

print("Class Average:", class_average)

print("Students performing above class average:",
      above_average)

Student Performance Analysis
--------------------------------
Student 1
Total: 253
Average: 84.33333333333333
Highest: 90
Lowest: 78

Student 2
Total: 217
Average: 72.33333333333333
Highest: 80
Lowest: 65

Student 3
Total: 263
Average: 87.66666666666667
Highest: 91
Lowest: 84

Student 4
Total: 188
Average: 62.666666666666664
Highest: 70
Lowest: 56

Student 5
Total: 276
Average: 92.0
Highest: 95
Lowest: 89

Class Average: 79.8
Students performing above class average: [1 3 5]
